Electrostatic site potentials (in V) using Ewald splitting parameter 3.14
This first parameter is a default value that was determined by LOBSTER

  atom#    atom      Potential       Potential
                    (Mulliken)       (Loewdin)
      1      Ru         -15.64          -14.01 
      2      Ru         -15.58          -14.00 
      3      Ru         -15.72          -14.03 
      4      Ru         -15.59          -14.00 
      5       O           9.12            8.22 
      6       O           9.13            8.22 
      7       O           6.54            5.89 
      8       O           6.70            5.93 
      9       O           6.66            5.91 
     10       O           9.09            8.21 
     11       O           9.13            8.22 
     12       O           6.58            5.91 
     13       O           6.66            5.91 
     14       O           6.70            5.93 

Madelung Energy (eV)    -68.45          -54.99 
